export interface Product {
  id: string;
  name: string;
  category: string;
  price: number; // USD
  dosage: string; // e.g., "500 mg", "10 mg/mL"
  quantity: string; // e.g., "30 Capsules", "150 mL Bottle"
  description: string;
  inStock: boolean;
  stockCount: number;
  badge?: string;
  amountUSD: number;
  isPrescriptionRequired: boolean; // NEW: Rx vs OTC flag
}

export const productDatabase: Product[] = [
  // ===== BABY CARE =====
  {
    id: "baby-001",
    name: "Infant Acetaminophen Suspension",
    category: "Baby Care",
    price: 7.99,
    dosage: "160 mg/5 mL",
    quantity: "120 mL Bottle",
    description: "Fever and pain relief for infants. Dye-free formula.",
    inStock: true,
    stockCount: 67,
    badge: "OTC",
    amountUSD: 7.99,
    isPrescriptionRequired: false,
  },
  {
    id: "baby-002",
    name: "Baby Moisturizing Lotion",
    category: "Baby Care",
    price: 9.99,
    dosage: "N/A",
    quantity: "200 mL Bottle",
    description: "Hypoallergenic, fragrance-free lotion for sensitive skin.",
    inStock: true,
    stockCount: 145,
    badge: "OTC",
    amountUSD: 9.99,
    isPrescriptionRequired: false,
  },
  {
    id: "baby-003",
    name: "Pediatric Electrolyte Solution",
    category: "Baby Care",
    price: 6.49,
    dosage: "Oral Rehydration",
    quantity: "500 mL Bottle",
    description: "Balances fluids and electrolytes. WHO-formulated.",
    inStock: true,
    stockCount: 201,
    badge: "OTC",
    amountUSD: 6.49,
    isPrescriptionRequired: false,
  },

  // ===== COLD & FLU (Distinct items, no duplicates) =====
  {
    id: "coldflu-001",
    name: "Guaifenesin 600mg ER Tablets",
    category: "Cold & Flu",
    price: 8.99,
    dosage: "600 mg Extended Release",
    quantity: "20 Tablets",
    description: "Expectorant for productive cough. 12-hour relief.",
    inStock: true,
    stockCount: 89,
    badge: "OTC",
    amountUSD: 8.99,
    isPrescriptionRequired: false,
  },
  {
    id: "coldflu-002",
    name: "Dextromethorphan HBr Cough Syrup",
    category: "Cold & Flu",
    price: 6.49,
    dosage: "10 mg/5 mL",
    quantity: "240 mL Bottle",
    description: "Non-drowsy cough suppressant. Fast-acting formula.",
    inStock: true,
    stockCount: 156,
    badge: "OTC",
    amountUSD: 6.49,
    isPrescriptionRequired: false,
  },
  {
    id: "coldflu-003",
    name: "Pseudoephedrine HCl 30mg Tablets",
    category: "Cold & Flu",
    price: 5.99,
    dosage: "30 mg Immediate Release",
    quantity: "24 Tablets",
    description: "Decongestant for nasal congestion. 4-6 hour relief.",
    inStock: true,
    stockCount: 234,
    badge: "OTC",
    amountUSD: 5.99,
    isPrescriptionRequired: false,
  },

  // ===== WELLNESS =====
  {
    id: "wellness-001",
    name: "Multivitamin Plus",
    category: "Wellness",
    price: 12.99,
    dosage: "Complete Formula",
    quantity: "60 Capsules",
    description: "Daily multivitamin with minerals and antioxidants.",
    inStock: true,
    stockCount: 45,
    badge: "OTC",
    amountUSD: 12.99,
    isPrescriptionRequired: false,
  },
  {
    id: "wellness-002",
    name: "Vitamin C 1000mg Tablets",
    category: "Wellness",
    price: 8.99,
    dosage: "1000 mg",
    quantity: "100 Tablets",
    description: "Immune support. Non-GMO, no added sugar.",
    inStock: true,
    stockCount: 89,
    badge: "OTC",
    amountUSD: 8.99,
    isPrescriptionRequired: false,
  },
  {
    id: "wellness-003",
    name: "Omega-3 Fish Oil Softgels",
    category: "Wellness",
    price: 14.99,
    dosage: "1000 mg per softgel",
    quantity: "60 Softgels",
    description: "Heart and brain health support with EPA/DHA.",
    inStock: true,
    stockCount: 72,
    badge: "OTC",
    amountUSD: 14.99,
    isPrescriptionRequired: false,
  },
  {
    id: "wellness-004",
    name: "Probiotic Capsules",
    category: "Wellness",
    price: 16.99,
    dosage: "10 Billion CFU",
    quantity: "30 Capsules",
    description: "Digestive health and gut flora support.",
    inStock: true,
    stockCount: 58,
    badge: "OTC",
    amountUSD: 16.99,
    isPrescriptionRequired: false,
  },
  {
    id: "wellness-005",
    name: "Magnesium Glycinate 400mg",
    category: "Wellness",
    price: 11.99,
    dosage: "400 mg Elemental Magnesium",
    quantity: "90 Tablets",
    description: "Sleep and muscle relaxation support.",
    inStock: true,
    stockCount: 134,
    badge: "OTC",
    amountUSD: 11.99,
    isPrescriptionRequired: false,
  },

  // ===== FIRST AID =====
  {
    id: "firstaid-001",
    name: "Antibiotic Ointment Triple",
    category: "First Aid",
    price: 4.99,
    dosage: "Neomycin 3.5mg/g",
    quantity: "1 oz Tube",
    description: "Prevents infection in minor cuts and scrapes.",
    inStock: true,
    stockCount: 203,
    badge: "OTC",
    amountUSD: 4.99,
    isPrescriptionRequired: false,
  },
  {
    id: "firstaid-002",
    name: "Hydrocortisone Cream 1%",
    category: "First Aid",
    price: 6.49,
    dosage: "1% Hydrocortisone",
    quantity: "1 oz Tube",
    description: "Anti-itch relief for minor skin irritations.",
    inStock: true,
    stockCount: 118,
    badge: "OTC",
    amountUSD: 6.49,
    isPrescriptionRequired: false,
  },
  {
    id: "firstaid-003",
    name: "Bandage Assortment Box",
    category: "First Aid",
    price: 3.99,
    dosage: "Sterile Gauze & Tape",
    quantity: "120 Pieces",
    description: "Comprehensive first aid bandages and gauze pads.",
    inStock: true,
    stockCount: 312,
    badge: "OTC",
    amountUSD: 3.99,
    isPrescriptionRequired: false,
  },

  // ===== VITAMINS =====
  {
    id: "vitamin-001",
    name: "Vitamin D3 2000 IU",
    category: "Vitamins",
    price: 9.99,
    dosage: "2000 IU",
    quantity: "100 Softgels",
    description: "Bone and immune system support.",
    inStock: true,
    stockCount: 176,
    badge: "OTC",
    amountUSD: 9.99,
    isPrescriptionRequired: false,
  },
  {
    id: "vitamin-002",
    name: "Vitamin B12 Sublingual",
    category: "Vitamins",
    price: 7.49,
    dosage: "1000 mcg",
    quantity: "60 Tablets",
    description: "Energy and nervous system support.",
    inStock: true,
    stockCount: 89,
    badge: "OTC",
    amountUSD: 7.49,
    isPrescriptionRequired: false,
  },
  {
    id: "vitamin-003",
    name: "Iron Supplement with Vitamin C",
    category: "Vitamins",
    price: 10.99,
    dosage: "18 mg Iron + 75 mg Vitamin C",
    quantity: "60 Tablets",
    description: "Iron absorption enhanced with Vitamin C.",
    inStock: true,
    stockCount: 45,
    badge: "OTC",
    amountUSD: 10.99,
    isPrescriptionRequired: false,
  },

  // ===== HERBAL =====
  {
    id: "herbal-001",
    name: "Turmeric Curcumin Extract",
    category: "Herbal",
    price: 14.99,
    dosage: "500 mg per capsule",
    quantity: "60 Capsules",
    description: "Natural anti-inflammatory and antioxidant support.",
    inStock: true,
    stockCount: 92,
    badge: "OTC",
    amountUSD: 14.99,
    isPrescriptionRequired: false,
  },
  {
    id: "herbal-002",
    name: "Ginger Root Extract",
    category: "Herbal",
    price: 11.99,
    dosage: "400 mg per capsule",
    quantity: "90 Capsules",
    description: "Digestive support and anti-nausea properties.",
    inStock: true,
    stockCount: 156,
    badge: "OTC",
    amountUSD: 11.99,
    isPrescriptionRequired: false,
  },
  {
    id: "herbal-003",
    name: "Ashwagandha Root Powder",
    category: "Herbal",
    price: 13.99,
    dosage: "450 mg per capsule",
    quantity: "60 Capsules",
    description: "Stress relief and adaptogenic support.",
    inStock: true,
    stockCount: 134,
    badge: "OTC",
    amountUSD: 13.99,
    isPrescriptionRequired: false,
  },

  // ===== PRESCRIPTION MEDICATIONS (with Rx flag) =====
  {
    id: "rx-001",
    name: "Metformin 500mg Tablets",
    category: "Prescription",
    price: 24.99,
    dosage: "500 mg",
    quantity: "60 Tablets",
    description: "Type 2 diabetes management. Requires valid prescription.",
    inStock: true,
    stockCount: 78,
    badge: "Rx",
    amountUSD: 24.99,
    isPrescriptionRequired: true,
  },
  {
    id: "rx-002",
    name: "Lisinopril 10mg Tablets",
    category: "Prescription",
    price: 19.99,
    dosage: "10 mg",
    quantity: "30 Tablets",
    description: "Blood pressure management. Requires valid prescription.",
    inStock: true,
    stockCount: 105,
    badge: "Rx",
    amountUSD: 19.99,
    isPrescriptionRequired: true,
  },
  {
    id: "rx-003",
    name: "Atorvastatin 20mg Tablets",
    category: "Prescription",
    price: 22.99,
    dosage: "20 mg",
    quantity: "30 Tablets",
    description: "Cholesterol management. Requires valid prescription.",
    inStock: true,
    stockCount: 89,
    badge: "Rx",
    amountUSD: 22.99,
    isPrescriptionRequired: true,
  },
];
